[project]
name = "mcp"
version = "0.1.0"
description = "A simple chainlit app to interact with the MCP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.4.400",
    "mcp[cli]>=1.6.0",
    "openai>=1.69.0",
    "python-dotenv>=1.1.0",
]
